// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOYESCsXbuZabAbfQWcXZHtdT3hD9Jk7s',
    appId: '1:537083231824:web:d400efb1e49b1ecdba9b55',
    messagingSenderId: '537083231824',
    projectId: 'fureverfriends-9c3b5',
    authDomain: 'fureverfriends-9c3b5.firebaseapp.com',
    storageBucket: 'fureverfriends-9c3b5.firebasestorage.app',
    measurementId: 'G-TESC70KFZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JZPKu6eYzDO9x0i0jr5UX67Ir2IcINs',
    appId: '1:537083231824:android:d868b80600abf747ba9b55',
    messagingSenderId: '537083231824',
    projectId: 'fureverfriends-9c3b5',
    storageBucket: 'fureverfriends-9c3b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-OixLgtFQnuh7DH8sD1GH_MhLoY6_AQ',
    appId: '1:537083231824:ios:507d18545d847560ba9b55',
    messagingSenderId: '537083231824',
    projectId: 'fureverfriends-9c3b5',
    storageBucket: 'fureverfriends-9c3b5.firebasestorage.app',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE-OixLgtFQnuh7DH8sD1GH_MhLoY6_AQ',
    appId: '1:537083231824:ios:507d18545d847560ba9b55',
    messagingSenderId: '537083231824',
    projectId: 'fureverfriends-9c3b5',
    storageBucket: 'fureverfriends-9c3b5.firebasestorage.app',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOYESCsXbuZabAbfQWcXZHtdT3hD9Jk7s',
    appId: '1:537083231824:web:d95fd266041e37e8ba9b55',
    messagingSenderId: '537083231824',
    projectId: 'fureverfriends-9c3b5',
    authDomain: 'fureverfriends-9c3b5.firebaseapp.com',
    storageBucket: 'fureverfriends-9c3b5.firebasestorage.app',
    measurementId: 'G-ND8XHBK98T',
  );
}
